version: '3'
services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
#      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret
      - POSTGRES_MULTIPLE_DATABASES=customer,account

  zookeeper:
    image: bitnami/zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
#    volumes:
#      - zookeeper:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
#    volumes:
#      - kafka:/bitnami/kafka
    links:
      - zookeeper

  axon-server:
    image: axoniq/axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
#    volumes:
#      - axon-server-data:/data
#      - axon-server-events:/eventdata
    environment:
      - AXONIQ_AXONSERVER_NAME=E-Shop Axon Server
      - AXONIQ_AXONSERVER_HOSTNAME=localhost
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true

#volumes:
#  zookeeper:
#  kafka:
#  axon-server-data:
#  axon-server-events:
#  postgres
